### ISSUE TITLE
Incompatible with build-mode

### ISSUE THREAD

**Issue by Silverfeelin** [Silverfeelin/Starbound-ManipulatedUI#4]
https://github.com/Ilazki/build-mode

I noticed this mod on Reddit, and checked for MUI compatibility. As it seems, it already has the patches for the controls implemented. There is, however, an issue when opening the interface.

`[Error] Exception while calling script init: (LuaException) Error code 2, [string "/interface/scripted/mmupgrade/mmupgradegui.lu..."]:77: bad argument #1 to 'pairs' (table expected, got nil)`

Line in question:  
`for k, v in pairs(self.upgradeConfig) do`

I believe this issue is caused by `mmbm.lua` of the build-mode mod calling updateGui before it is ready (when shadowing the init function). Manipulated UI calls the init function of interfaces when they are selected, not when the interface loads. Since `updateGui()` expects the matter manipulator upgrade panel to be initialized, it also expects variables to be declared that haven't been declared yet.

Fixing this issue shouldn't take too much effort, and I'll look into it when I have the time on my hands. It's probably as simple as setting a boolean in the init, and only allowing this `updateGui()` to run code when initialized.

**Comment by Ilazki** [comment]
For what it's worth, the problem was happening because I was calling `updateGui()` during init like you said.  I haven't had a chance to look into it further, but when I found out about it yesterday I removed the explicit updateGui call as a workaround.

The reason for the call was to force BM and Matter Manipulator Manipulator to update their values faster, since there's a noticeable delay between the upgrade UI appearing and the next updateGui call (which fixes them) when MUI isn't in use. The delay only happens the very first time the UI is opened, trivial compared to breaking MUI, so I reverted it as soon as I saw.  I should have noticed it sooner, but I had MUI disabled to make sure nothing was broken for regular users and forgot to re-enable it after. 

Also, saw the merge request; will check into that when I have a chance and see if it affects anything, since I'm relying pretty heavily on BM loading late in the mod loading process.

**Comment by Silverfeelin** [comment]
Having Manipulated UI in the includes forces BM to load after MUI, but there can still be mods loaded between them.
You can add "priority": 99999 (or whatever 'high' value you desire) to the metadata. In most cases this will cause the mod to load last.

I did a quick test on the bus and returning prematurely in the updateGui function (if the init hasn't been called yet) seems to fix the issue. Currently don't have the time to do proper testing, will do so later.

**Comment by Ilazki** [comment]
I just got a chance to pull the wip branch to test it and you're right, everything seems to be doing the right thing with it.  Forcing an update to remove the update delay for non-MUI users works as expected and there are no errors when attempting to do it while MUI is active.  

For now I'll leave the forced `updateGui` call disabled, and I'll re-enable it whenever you finish testing and push out the MUI change.

Glad it ended up resulting in a good change, but I still can't believe I didn't catch the problem *before* putting the update on the workshop.  Like I've said elsewhere, I explicitly test with MUI and MMM installed because 1) I already use them and 2) I know they're commonly installed, but I had to turn MUI off to make sure I didn't break anything for people not using it, then completely forgot to turn it back on later. Oops ;(

**Comment by Silverfeelin** [comment]
The changes to MUI I made seem to fully solve the issue (together with the pull request I made on your mod). I have notified @Mehgugs to create a new release (since he's the only one that can push updated on the Steam Workshop).

Changes: https://github.com/Silverfeelin/Starbound-ManipulatedUI/commit/191d8a270d67b2c2c9d2d4e6b7818ca86d669b12
